AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - Rakefile

  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 115
  Exclude: [Gemfile]

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: false
  EnforcedStyleForMultiline: consistent_comma

Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: integral
